### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by jaonoctus** [jaonoctus/exchange#6]
- Migrations are in `/database/migrations`
- Models are in `/app`

![screenshot from 2018-02-19 16-14-39](https://user-images.githubusercontent.com/7918067/36393820-0364f82e-1590-11e8-8b01-ddd977ea1d7b.png)

# TODO
- [x] Fix decimals `precision` and `scale`.
- [ ] Move models to `/app/models` folder. `in progress`
- [ ] Use [laravel-auditing](https://github.com/owen-it/laravel-auditing) to track changes.

**Comment by jaonoctus** [comment]
@vjoao @ibrunotome

What about it, guys?

**Comment by ibrunotome** [comment]
Hi, I think the decimal fields can't be 8,2, because much of the orders will be a big fraction like 0,00724 for example. I suggest a 16,8 like the binance uses.

- I suggest move the models to a folder called Models in /app too.
- Not related to the structure, but I suggest to use the laravel-auditing package too to track every single change on the models.

**Comment by jaonoctus** [comment]
@ibrunotome I totally agree!

I've updated this issue with a "TODO" section.

Thanks

**Comment by vinyvicente** [comment]
@jaonoctus, uses uuid in public reference (orders, by example), id integer is vulnerable, principally to inspect element, etc :)

**Comment by vjoao** [comment]
@vinyvicente Order information is already public. As UUIDs are 4 times larger than integers, this might reflect in storage problems in the future.

**Comment by jaonoctus** [comment]
@vinyvicente, I agree with @vjoao. But, for sensitive data, we can use [hashids](http://hashids.org/php/).
