### ISSUE TITLE
Order Form

### ISSUE THREAD

**Issue by jaonoctus** [jaonoctus/exchange#7]
# Preview
![screenshot from 2018-02-19 13-19-36](https://user-images.githubusercontent.com/7918067/36387390-95512244-1577-11e8-9dca-779f4b76cdf2.png)

# TODO
- [ ] Write tests. `in progress`
- [ ] Order type (Limit/Market/Stop/Stop-Limit).
- [ ] Copy an open order from order book.
- [ ] Validate balances before place an order.
- [ ] Prevent invalid inputs ([vue-the-mask](https://vuejs-tips.github.io/vue-the-mask/)). `in progress`
- [x] Order action (buy/sell).
- [x] Calculate Total, when type Amount or Price.
- [x] Calculate Amount, when type Total.
- [x] Set Price field to current highest pair bid (buy).
- [x] Set Price field to current lowest pair ask (sell).
- [x] Calculate max Amount using available balance.
- [x] Calculate max Total using available balance.
